Repository ryan95f/yamlator, pull requests merged in 2022-05, with the labels that each got.

#24 Support for Ints & Floats in Enums
  changelog.md
  docs/schema_components.md
  example/project.ys
  src/grammer/grammer.lark
  src/parser.py
  src/validators.py
  tests/parser/test_schema_transformer.py
  tests/validators/test_enum_type_validator.py
Labels: documentation, enhancement

#27 Miscellaneous repository improvements
  Makefile
  README.md
  example/README.md
  example/person.yaml
  example/person.ys
  example/person/person.yaml
  example/person/person.ys
  example/project/project.yaml
  example/project/project.ys
  setup.py
  src/violations.py
  tests/violations/test_violation_json_encoder.py
Labels: documentation

#28 Boolean validator
  docs/schema_components.md
  example/person/person.ys
  src/grammer/grammer.lark
  src/parser.py
  src/types.py
  src/validators.py
  src/validators/__init__.py
  src/validators/any_type_validator.py
  src/validators/base_validator.py
  src/validators/builtin_type_validator.py
  src/validators/core.py
  src/validators/enum_type_validator.py
  src/validators/list_validator.py
  src/validators/map_validator.py
  src/validators/optional_validator.py
  src/validators/regex_validator.py
  src/validators/required_validator.py
  src/validators/ruleset_validator.py
  tests/parser/test_schema_transformer.py
  tests/validators/test_builtin_type_validator.py
Labels: enhancement

#29 Ruleset & Enum construct name fix
  README.md
  changelog.md
  docs/schema_components.md
  docs/setting_up_the_environment.md
  setup.cfg
  setup.py
  src/grammer/grammer.lark
  tests/files/example/example.yaml
  tests/files/example/example.ys
Labels: bug, documentation

#30 Schema components doc improvements
  docs/schema_components.md
Labels: documentation

#32 url-update
  README.md
  changelog.md
  setup.py
Labels: documentation
